# Generated by Django 4.2.13 on 2024-11-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.TextField(blank=True)),
                ('nombre', models.TextField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('cp', models.IntegerField()),
                ('usocfdi', models.TextField(default='G03')),
                ('metododepago', models.TextField(default='PUE')),
                ('formadepago', models.TextField(default='01')),
                ('tipocomprobante', models.TextField(default='E')),
                ('contacto', models.TextField(default='')),
                ('diascredito', models.IntegerField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('listacompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='precios.lista')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
