# Generated by Django 4.2.13 on 2024-11-07 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat40', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('modelo', models.TextField(blank=True, default='')),
                ('precio', models.FloatField(default=0)),
                ('noidentificacion', models.TextField(default='')),
                ('codigobarras', models.TextField(default='')),
                ('descuento', models.FloatField(default=0)),
                ('trasladoiva', models.FloatField(default=0)),
                ('trasladoieps', models.FloatField(default=0)),
                ('retencioniva', models.FloatField(default=0)),
                ('retencionisr', models.FloatField(default=0)),
                ('retencionieps', models.FloatField(default=0)),
                ('existencias', models.FloatField(default=0)),
                ('stockmin', models.FloatField(default=1)),
                ('stockmax', models.FloatField(default=1)),
                ('claveunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat40.claveunidad')),
                ('codigosat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat40.claveprodserv')),
                ('linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='links.linea')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='links.marca')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
