# Generated by Django 4.2.13 on 2024-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.TextField(blank=True, null=True)),
                ('codigopostal', models.TextField(blank=True, null=True)),
                ('nombre_asentamiento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('clave_transporte', models.TextField(blank=True, null=True)),
                ('nacionalidad', models.TextField(blank=True, null=True)),
                ('designador_iata', models.TextField(blank=True, null=True)),
                ('linea_ferrea', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
