# Generated by Django 4.2.13 on 2024-11-08 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('cintura', models.IntegerField(default=0)),
                ('cadera', models.IntegerField(default=0)),
                ('actfisica', models.IntegerField(default=0)),
                ('actfisican', models.IntegerField(default=0)),
                ('bebidasugar', models.IntegerField(default=0)),
                ('bebidasugarn', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
