# Generated by Django 4.2.13 on 2024-11-10 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innsalud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
