# Generated by Django 4.2.13 on 2024-11-25 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innsalud', '0002_record_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('apellido', models.TextField(default='')),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.IntegerField(default=0)),
                ('email', models.TextField(default='')),
                ('diabetes', models.IntegerField(default=0)),
                ('diabetesp', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
