# Generated by Django 4.2.13 on 2024-11-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.TextField(default='')),
                ('folio', models.TextField(default='')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('formapago', models.TextField(default='')),
                ('condicionesdepago', models.TextField(default='')),
                ('subtotal', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('moneda', models.TextField(default='')),
                ('tipodecomprobante', models.TextField(default='')),
                ('metodopago', models.TextField(default='')),
                ('lugarexpedicion', models.TextField(default='')),
                ('totalimpuestostrasladados', models.FloatField(default=0)),
                ('totalimpuestosretenidos', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('statusv', models.TextField(default='')),
                ('statuscfdi', models.TextField(default='')),
                ('xml', models.TextField(default='')),
                ('pdf', models.TextField(default='')),
                ('complpago', models.TextField(default='')),
                ('complneg', models.TextField(default='')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='receptor.receptor')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('importe', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('trasladoiva', models.FloatField(default=0)),
                ('trasladoieps', models.FloatField(default=0)),
                ('retencioniva', models.FloatField(default=0)),
                ('retencionisr', models.FloatField(default=0)),
                ('retencionieps', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='links.link')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', related_query_name='detail', to='sales.sale')),
            ],
        ),
    ]
